export enum ErrorCodeEnum {
  SERVER_ERROR = 'SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_USER = 'INVALID_USER',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TRANSACTIONAL_CODE_NOT_MATCH = 'TRANSACTIONAL_CODE_NOT_MATCH',
  TRANSACTIONAL_CODE_USED = 'TRANSACTIONAL_CODE_USED',
  TRANSACTIONAL_CODE_EXPIRED = 'TRANSACTIONAL_CODE_EXPIRED',
}
